### ISSUE TITLE
Daemon stops accepting new entries until restarted

### ISSUE THREAD

**Issue by butters16** [manbearwiz/flexget-dockerfile#3]
# Description

I often get issues where the scheduler daemon seems to be stuck and no new entries are accepted. The docker logs vary. I've included some recent ones below. The easiest thing to do is restart the container, but I've found that attaching to the container and executing a `flexget execute` will work (and accept new entries) and a `flexget daemon status` indicates the daemon is fine. Not even a `flexget daemon stop && flexget daemon start` will fix the problem. I'd like to know if others are experiencing the same problem. I've read that the flexget daemon has issues, so I'm considering abandoning the daemon for a more archaic infinite loop of `flexget execute` and sleep.
# Recent Docker Logs
1. OperationalError: (sqlite3.OperationalError) disk I/O error [SQL: u'SELECT apscheduler_jobs.next_run_time \nFROM apscheduler_jobs \nWHERE apscheduler_jobs.next_run_time IS NOT NULL ORDER BY apscheduler_jobs.next_run_time\n LIMIT ? OFFSET ?'] [parameters: (1, 0)]
2. Socket error: [Errno -2] Name or service not known
   2015-11-21 08:17 WARNING  requests.packages.urllib3.connectionpool _removed_            Retrying (Retry(total=0, connect=None, read=None, redirect=0)) after connection broken by 'NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f7ae42e8350>: Failed to establish a new connection: [Errno -2] Name or service not known',)'
3. RequestException: HTTPConnectionPool(host='_removed_', port=80): Max retries exceeded with url: _removed_ (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f7ae42e8990>: Failed to establish a new connection: [Errno -2] Name or service not known',))

**Comment by manbearwiz** [comment]
I am not running into this issue. Out of curiosity I `grep`'d my logs for the errors above and came up with nothing.

Error 1 seems to be an issue reading and writing to the db. Is the `/flexget` volume mounted correctly? What are the permissions?

Errors 2 and 3 appear are internet connection issues. The next time u see the error try `ping`ing the host that it says it cannot create a connection with. This may just be that their server is down.

If nothing else, you might try talking with the people of flexget to see if they can provide more insight into this. If you do resolve this make sure to submit a PR or at the very least let me know what your issue was.

**Comment by butters16** [comment]
Thanks for the info. I that case, it must be my configuration. I'm most suspicious of my tight scheduling interval, 1 minute. I've switched over to `CMD rm -f /flexget/.config-lock && while :; do flexget execute --cron; sleep 1m; done` in the Dockerfile and removed all scheduling from the config.yml. I'll post back how that goes after a while.

FYI, I was able to successfully ping while attaching to containers that has these logs. For some reason, I did not think to ping the host in question, but like I said before, executing `flexget exec` (which uses the host in question) manually worked fine.

**Comment by butters16** [comment]
`CMD rm -f /flexget/.config-lock && while :; do flexget execute --cron; sleep 1m; done` eventually resulted in an infinite
_Invalid lock file. Make sure FlexGet is not running, then delete it._

I switched over to `CMD while :; do rm -f /flexget/.config-lock; flexget execute; sleep 1m; done` (without the `--cron`) and it's been running well for 4 days. I've seen 2 instances of above _NewConnectionError_, but the script continued and produced results the next minute. That's acceptable for my application.

This is obviously a super hack, but it gives me some food for thought. I'm thinking concurrency has been my problem. I think the flexget daemon and the `--cron` flag allow the system to background maintenance. I suspect that does not play well with deleting the lock file and running every minute.
