### ISSUE TITLE
Flexget doesn't update to latest version

### ISSUE THREAD

**Issue by Loader23** [manbearwiz/flexget-dockerfile#6]
Hi,

you said the version of Flexget installed will soley depend on the latest version available in the Python Package Index. It seems that this is not working anymore and is stuck at 2.13.14. Python Index says 2.13.23.

Maybe it has to do something with this but iam no expert^^:
https://discuss.flexget.com/t/cant-upgrade-past-2-13-14-discovery-0-0-4-has-requirement-requests-2-5-0/4179

Did the requirements changed maybe?

**Comment by manbearwiz** [comment]
Docker hub was supposed to be set up to build new images when new flexget versions are released. I just triggered it manually, so once those are done building we will see what version they end up with.

**Comment by manbearwiz** [comment]
The `alpine-python3` image just finished rebuilding and logs confirm it to have `2.13.23`. Other images should be finishing up in the next couple minutes. Going to close this issue for now. Pull it down and let me know if it works for you.

**Comment by Loader23** [comment]
Yep, its up-to-date and working. Thanks alot :-)

**Comment by Loader23** [comment]
It does not update again :-( While this is not that critical at this moment it might become a problem in the future. Please fix :-)

**Comment by Loader23** [comment]
Hi @manbearwiz ,
is there a way to update to the latest version with a command in shell? So you don't have to build a new Image every time?

**Comment by manbearwiz** [comment]
Just [shell into the running container](https://askubuntu.com/a/507009) and do `sudo pip install flexget --upgrade`

**Comment by Loader23** [comment]
Awesome, thanks alot :-) 👍
